language: php
php:
  - '7.2'
addons:
  sonarcloud:
    organization: 'phikremer-github'
    token:
      secure: $SONAR_TOKEN
before_script:
  - 'composer install'
script:
  - 'mkdir test/reports'
  - 'vendor/bin/phpunit'
  - 'sonar-scanner'

