language: php
php:
  - '7.2'
addons:
  sonarcloud:
    organization: 'phikremer-github'
    token:
      secure: $SONAR_TOKEN
before_script:
  - 'composer install --dev'
script:
  - 'cd test && ../vendor/bin/phpunit'
  - 'sonar-scanner'

